import type { MetricDefinition } from "./types";

/**
 * Catálogo único de métricas del producto.
 *
 * `materiality` es la brecha a partir de la cual la diferencia deja de ser
 * ruido, expresada en la escala que indica `gapScale` (tanto por uno del valor
 * del competidor, o puntos porcentuales). Los valores no son arbitrarios: son
 * más exigentes en métricas con mucha varianza natural entre empresas
 * (seguidores, tráfico) y más sensibles en las que una diferencia pequeña ya
 * es estructural (margen, retención).
 */
export const METRICS: readonly MetricDefinition[] = [
  // ── General ────────────────────────────────────────────────
  {
    id: "nombre",
    label: "Nombre",
    help: "Nombre comercial de la empresa.",
    section: "general",
    area: "organizacion",
    format: "text",
    direction: "neutral",
    weight: 1,
    materiality: 1,
    comparable: false,
  },
  {
    id: "sector",
    label: "Sector",
    help: "Actividad principal. Dos empresas de sectores distintos no son comparables punto a punto.",
    section: "general",
    area: "organizacion",
    format: "text",
    direction: "neutral",
    weight: 1,
    materiality: 1,
    comparable: false,
  },
  {
    id: "pais",
    label: "País",
    help: "Mercado principal en el que opera.",
    section: "general",
    area: "organizacion",
    format: "text",
    direction: "neutral",
    weight: 1,
    materiality: 1,
    comparable: false,
  },
  {
    id: "tamano",
    label: "Tamaño de la empresa",
    help: "Clasificación por volumen y plantilla.",
    section: "general",
    area: "organizacion",
    format: "enum",
    direction: "neutral",
    weight: 1,
    materiality: 1,
    comparable: false,
    options: ["Autónomo", "Micro", "Pequeña", "Mediana", "Grande"],
  },
  {
    id: "empleados",
    label: "Número de empleados",
    help: "Plantilla equivalente a jornada completa.",
    section: "general",
    area: "organizacion",
    format: "number",
    direction: "neutral",
    weight: 2,
    materiality: 0.2,
    min: 0,
    comparable: true,
  },
  {
    id: "anioCreacion",
    label: "Año de creación",
    help: "Año de constitución. Sirve para contextualizar madurez y crecimiento.",
    section: "general",
    area: "organizacion",
    format: "number",
    direction: "neutral",
    weight: 1,
    materiality: 1,
    min: 1800,
    max: 2100,
    comparable: false,
  },

  // ── Finanzas ───────────────────────────────────────────────
  {
    id: "facturacion",
    label: "Facturación",
    help: "Ingresos totales de los últimos 12 meses, sin impuestos.",
    section: "finanzas",
    area: "finanzas",
    format: "currency",
    direction: "higher",
    weight: 3,
    materiality: 0.1,
    min: 0,
    comparable: true,
  },
  {
    id: "beneficio",
    label: "Beneficio",
    help: "Resultado después de todos los gastos del periodo.",
    section: "finanzas",
    area: "finanzas",
    format: "currency",
    direction: "higher",
    weight: 3,
    materiality: 0.1,
    comparable: true,
  },
  {
    id: "margen",
    label: "Margen",
    help: "Beneficio dividido entre facturación, en porcentaje.",
    section: "finanzas",
    area: "finanzas",
    format: "percent",
    direction: "higher",
    weight: 3,
    materiality: 0.03,
    gapScale: "points",
    min: -100,
    max: 100,
    comparable: true,
  },
  {
    id: "costes",
    label: "Costes totales",
    help: "Suma de todos los gastos del periodo. Se muestra como contexto: comparar costes absolutos entre empresas de distinto tamaño no dice nada, porque crecen con la facturación. Lo que sí compara es el margen.",
    section: "finanzas",
    area: "finanzas",
    format: "currency",
    // Neutral a propósito: tener menos costes no es una ventaja si también se
    // factura menos. La comparación útil la hace el margen.
    direction: "neutral",
    weight: 2,
    materiality: 0.1,
    min: 0,
    comparable: true,
  },
  {
    id: "deuda",
    label: "Deuda",
    help: "Deuda financiera viva a cierre del periodo.",
    section: "finanzas",
    area: "finanzas",
    format: "currency",
    direction: "lower",
    weight: 2,
    materiality: 0.15,
    min: 0,
    comparable: true,
  },
  {
    id: "flujoCaja",
    label: "Flujo de caja",
    help: "Caja generada por la actividad en los últimos 12 meses.",
    section: "finanzas",
    area: "finanzas",
    format: "currency",
    direction: "higher",
    weight: 3,
    materiality: 0.12,
    comparable: true,
  },
  {
    id: "crecimientoAnual",
    label: "Crecimiento anual",
    help: "Variación de la facturación respecto al año anterior.",
    section: "finanzas",
    area: "finanzas",
    format: "percent",
    direction: "higher",
    weight: 3,
    materiality: 0.05,
    gapScale: "points",
    min: -100,
    comparable: true,
  },

  // ── Clientes ───────────────────────────────────────────────
  {
    id: "numClientes",
    label: "Número de clientes",
    help: "Clientes que han comprado al menos una vez en los últimos 12 meses.",
    section: "clientes",
    area: "clientes",
    format: "number",
    direction: "higher",
    weight: 3,
    materiality: 0.1,
    min: 0,
    comparable: true,
  },
  {
    id: "ticketMedio",
    label: "Ticket medio",
    help: "Importe medio por pedido o transacción.",
    section: "clientes",
    area: "clientes",
    format: "currency",
    direction: "higher",
    weight: 3,
    materiality: 0.1,
    min: 0,
    comparable: true,
  },
  {
    id: "frecuenciaCompra",
    label: "Frecuencia de compra",
    help: "Número medio de compras por cliente y año.",
    section: "clientes",
    area: "clientes",
    format: "perYear",
    direction: "higher",
    weight: 3,
    materiality: 0.1,
    min: 0,
    unit: "compras/año",
    comparable: true,
  },
  {
    id: "tasaRecompra",
    label: "Tasa de recompra",
    help: "Porcentaje de clientes que compran una segunda vez.",
    section: "clientes",
    area: "clientes",
    format: "percent",
    direction: "higher",
    weight: 3,
    materiality: 0.05,
    gapScale: "points",
    min: 0,
    max: 100,
    comparable: true,
  },
  {
    id: "retencion",
    label: "Retención",
    help: "Porcentaje de clientes que siguen activos al cabo de 12 meses.",
    section: "clientes",
    area: "clientes",
    format: "percent",
    direction: "higher",
    weight: 3,
    materiality: 0.05,
    gapScale: "points",
    min: 0,
    max: 100,
    comparable: true,
  },
  {
    id: "cac",
    label: "Coste de adquisición",
    help: "Cuánto cuesta de media conseguir un cliente nuevo (CAC).",
    section: "clientes",
    area: "marketing",
    format: "currency",
    direction: "lower",
    weight: 3,
    materiality: 0.12,
    min: 0,
    comparable: true,
  },
  {
    id: "satisfaccion",
    label: "Satisfacción",
    help: "Valoración media de los clientes, de 0 a 10.",
    section: "clientes",
    area: "clientes",
    format: "score",
    direction: "higher",
    weight: 2,
    materiality: 0.08,
    min: 0,
    max: 10,
    comparable: true,
  },

  // ── Producto ───────────────────────────────────────────────
  {
    id: "numProductos",
    label: "Número de productos",
    help: "Referencias o servicios distintos en catálogo.",
    section: "producto",
    area: "producto",
    format: "number",
    direction: "higher",
    weight: 2,
    materiality: 0.2,
    min: 0,
    comparable: true,
  },
  {
    id: "precioMedio",
    label: "Precio medio",
    help: "Precio medio de venta por unidad o servicio.",
    section: "producto",
    area: "producto",
    format: "currency",
    direction: "neutral",
    weight: 2,
    materiality: 0.12,
    min: 0,
    comparable: true,
  },
  {
    id: "calidadPercibida",
    label: "Calidad percibida",
    help: "Cómo valoran los clientes la calidad, de 0 a 10 (reseñas, encuestas).",
    section: "producto",
    area: "producto",
    format: "score",
    direction: "higher",
    weight: 2,
    materiality: 0.08,
    min: 0,
    max: 10,
    comparable: true,
  },
  {
    id: "frecuenciaLanzamiento",
    label: "Frecuencia de lanzamiento",
    help: "Novedades lanzadas al año.",
    section: "producto",
    area: "producto",
    format: "perYear",
    direction: "higher",
    weight: 2,
    materiality: 0.2,
    min: 0,
    unit: "lanzamientos/año",
    comparable: true,
  },
  {
    id: "diferenciacion",
    label: "Diferenciación",
    help: "Cuánto se distingue la oferta de la competencia, de 0 a 10.",
    section: "producto",
    area: "producto",
    format: "score",
    direction: "higher",
    weight: 2,
    materiality: 0.1,
    min: 0,
    max: 10,
    comparable: true,
  },

  // ── Marketing ──────────────────────────────────────────────
  {
    id: "presupuestoMarketing",
    label: "Presupuesto de marketing",
    help: "Inversión anual total en marketing.",
    section: "marketing",
    area: "marketing",
    format: "currency",
    direction: "neutral",
    weight: 2,
    materiality: 0.15,
    min: 0,
    comparable: true,
  },
  {
    id: "canalesSociales",
    label: "Redes sociales activas",
    help: "Número de canales con publicación regular.",
    section: "marketing",
    area: "marketing",
    format: "number",
    direction: "higher",
    weight: 1,
    materiality: 0.25,
    min: 0,
    comparable: true,
  },
  {
    id: "seguidores",
    label: "Seguidores",
    help: "Suma de seguidores en todos los canales.",
    section: "marketing",
    area: "marketing",
    format: "number",
    direction: "higher",
    weight: 1,
    materiality: 0.3,
    min: 0,
    comparable: true,
  },
  {
    id: "traficoWeb",
    label: "Tráfico web",
    help: "Visitas mensuales a la web.",
    section: "marketing",
    area: "digital",
    format: "number",
    direction: "higher",
    weight: 3,
    materiality: 0.15,
    min: 0,
    unit: "visitas/mes",
    comparable: true,
  },
  {
    id: "conversion",
    label: "Conversión web",
    help: "Porcentaje de visitas que terminan en compra o lead.",
    section: "marketing",
    area: "digital",
    format: "percent",
    direction: "higher",
    weight: 3,
    materiality: 0.15,
    gapScale: "relative",
    min: 0,
    max: 100,
    comparable: true,
  },
  {
    id: "seo",
    label: "Visibilidad SEO",
    help: "Fuerza del posicionamiento orgánico, de 0 a 100.",
    section: "marketing",
    area: "digital",
    format: "score",
    direction: "higher",
    weight: 2,
    materiality: 0.15,
    min: 0,
    max: 100,
    comparable: true,
  },
  {
    id: "inversionPublicidad",
    label: "Inversión en publicidad",
    help: "Gasto anual en publicidad de pago.",
    section: "marketing",
    area: "marketing",
    format: "currency",
    direction: "neutral",
    weight: 2,
    materiality: 0.2,
    min: 0,
    comparable: true,
  },
  {
    id: "coberturaEmail",
    label: "Cobertura de email marketing",
    help: "Porcentaje de clientes que reciben comunicaciones por email.",
    section: "marketing",
    area: "marketing",
    format: "percent",
    direction: "higher",
    weight: 2,
    materiality: 0.1,
    gapScale: "points",
    min: 0,
    max: 100,
    comparable: true,
  },
  {
    id: "colaboracionesInfluencers",
    label: "Colaboraciones con influencers",
    help: "Número de colaboraciones al año.",
    section: "marketing",
    area: "marketing",
    format: "perYear",
    direction: "higher",
    weight: 1,
    materiality: 0.3,
    min: 0,
    unit: "al año",
    comparable: true,
  },

  // ── Operaciones ────────────────────────────────────────────
  {
    id: "costeProduccion",
    label: "Coste de producción",
    help: "Coste medio de producir una unidad o prestar un servicio.",
    section: "operaciones",
    area: "operaciones",
    format: "currency",
    direction: "lower",
    weight: 3,
    materiality: 0.1,
    min: 0,
    comparable: true,
  },
  {
    id: "tiempoEntrega",
    label: "Tiempo de entrega",
    help: "Días medios desde el pedido hasta la entrega.",
    section: "operaciones",
    area: "operaciones",
    format: "days",
    direction: "lower",
    weight: 2,
    materiality: 0.15,
    min: 0,
    unit: "días",
    comparable: true,
  },
  {
    id: "devoluciones",
    label: "Tasa de devoluciones",
    help: "Porcentaje de pedidos devueltos.",
    section: "operaciones",
    area: "operaciones",
    format: "percent",
    direction: "lower",
    weight: 2,
    materiality: 0.25,
    gapScale: "relative",
    min: 0,
    max: 100,
    comparable: true,
  },
  {
    id: "rotacionInventario",
    label: "Rotación de inventario",
    help: "Veces que se renueva el inventario en un año.",
    section: "operaciones",
    area: "operaciones",
    format: "perYear",
    direction: "higher",
    weight: 2,
    materiality: 0.15,
    min: 0,
    unit: "veces/año",
    comparable: true,
  },
  {
    id: "costeLogistico",
    label: "Coste logístico",
    help: "Coste de logística como porcentaje de la facturación.",
    section: "operaciones",
    area: "operaciones",
    format: "percent",
    direction: "lower",
    weight: 2,
    materiality: 0.15,
    gapScale: "relative",
    min: 0,
    max: 100,
    comparable: true,
  },

  // ── Tecnología ─────────────────────────────────────────────
  {
    id: "automatizacion",
    label: "Nivel de automatización",
    help: "Cuánto del trabajo repetitivo está automatizado, de 0 a 10.",
    section: "tecnologia",
    area: "organizacion",
    format: "score",
    direction: "higher",
    weight: 2,
    materiality: 0.12,
    min: 0,
    max: 10,
    comparable: true,
  },
  {
    id: "usoIA",
    label: "Uso de IA",
    help: "Grado de uso de inteligencia artificial en el negocio, de 0 a 10.",
    section: "tecnologia",
    area: "digital",
    format: "score",
    direction: "higher",
    weight: 1,
    materiality: 0.2,
    min: 0,
    max: 10,
    comparable: true,
  },
  {
    id: "crm",
    label: "Madurez del CRM",
    help: "Nivel de uso real del CRM, de 0 a 10 (0 = no hay).",
    section: "tecnologia",
    area: "digital",
    format: "score",
    direction: "higher",
    weight: 2,
    materiality: 0.15,
    min: 0,
    max: 10,
    comparable: true,
  },
  {
    id: "analytics",
    label: "Madurez de analítica",
    help: "Capacidad de medir y decidir con datos, de 0 a 10.",
    section: "tecnologia",
    area: "digital",
    format: "score",
    direction: "higher",
    weight: 2,
    materiality: 0.15,
    min: 0,
    max: 10,
    comparable: true,
  },
  {
    id: "software",
    label: "Software utilizado",
    help: "Herramientas principales en uso. Texto libre, no se compara numéricamente.",
    section: "tecnologia",
    area: "digital",
    format: "text",
    direction: "neutral",
    weight: 1,
    materiality: 1,
    comparable: false,
  },
] as const;

/**
 * Métricas calculadas a partir de otras. No se piden en el formulario: se
 * derivan cuando los ingredientes están disponibles, y su procedencia siempre
 * queda marcada como `derived`.
 */
export const DERIVED_METRICS: readonly MetricDefinition[] = [
  {
    id: "facturacionPorEmpleado",
    label: "Facturación por empleado",
    help: "Facturación dividida entre la plantilla. Mide la productividad del equipo.",
    section: "finanzas",
    area: "organizacion",
    format: "currency",
    direction: "higher",
    weight: 3,
    materiality: 0.12,
    comparable: true,
    derivedFrom: ["facturacion", "empleados"],
  },
  {
    id: "valorAnualCliente",
    label: "Valor anual por cliente",
    help: "Ticket medio multiplicado por la frecuencia de compra anual.",
    section: "clientes",
    area: "clientes",
    format: "currency",
    direction: "higher",
    weight: 3,
    materiality: 0.1,
    comparable: true,
    derivedFrom: ["ticketMedio", "frecuenciaCompra"],
  },
  {
    id: "ratioValorCac",
    label: "Ratio valor / CAC",
    help: "Valor anual del cliente dividido entre el coste de adquirirlo. Por debajo de 1 se pierde dinero el primer año.",
    section: "clientes",
    area: "marketing",
    format: "number",
    direction: "higher",
    weight: 3,
    materiality: 0.15,
    unit: "×",
    comparable: true,
    derivedFrom: ["valorAnualCliente", "cac"],
  },
  {
    id: "ingresoPorVisita",
    label: "Ingreso por visita",
    help: "Cuánto ingresa de media cada visita a la web, combinando conversión y ticket.",
    section: "marketing",
    area: "digital",
    format: "currency",
    direction: "higher",
    weight: 2,
    materiality: 0.15,
    comparable: true,
    derivedFrom: ["conversion", "ticketMedio"],
  },
] as const;

export const ALL_METRICS: readonly MetricDefinition[] = [
  ...METRICS,
  ...DERIVED_METRICS,
];

const BY_ID = new Map(ALL_METRICS.map((m) => [m.id, m]));

export function getMetric(id: string): MetricDefinition | undefined {
  return BY_ID.get(id);
}

/** Lanza si el id no existe: usar cuando el id procede de código, no de datos. */
export function requireMetric(id: string): MetricDefinition {
  const metric = BY_ID.get(id);
  if (!metric) throw new Error(`Métrica desconocida: ${id}`);
  return metric;
}

export function metricsBySection(section: string): MetricDefinition[] {
  return METRICS.filter((m) => m.section === section);
}

export function metricsByArea(area: string): MetricDefinition[] {
  return ALL_METRICS.filter((m) => m.area === area);
}
